/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "serial.h"
#include "timer.h"
#include "stm32f303xc.h"
#include "digital_io.h"
#include "setup.h"
#include "handler.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void finished_transmission(uint32_t bytes_sent) {
	// This function will be called after a transmission is complete

	volatile uint32_t test = 0;
	// make a very simple delay
	for (volatile uint32_t i = 0; i < 0x8ffff; i++) {
		// waste time !
	}
}

void enableInterrupts()
{
	__disable_irq();

	// Generate an interrupt upon receiving data
	USART1->CR1 |= USART_CR1_RXNEIE_Msk;

	// Set priority and enable interrupts
	NVIC_SetPriority(USART1_IRQn, 1);
	NVIC_EnableIRQ(USART1_IRQn);

	__enable_irq();
}

int main(void)
{
//	enable_clocks();
//	initialise_board();

	SerialInitialise(BAUD_115200, &USART1_PORT, &finished_transmission);
	enableInterrupts();

	/* Loop forever */
	for(;;) {
//		SerialOutputString(string_to_send, &USART1_PORT);
	}
}


void blink_leds(void) {
	// This function will be called if there is a timer overflow
	static uint8_t led_state = 0;
	GPIOE->ODR = led_state ? 0xFF00 : 0x0000;  // Toggle LEDs on PE8-PE15
	led_state = !led_state;  // Flip the state
}

int timerdemo(void) {
	enable_clocks();
	initialise_board();
	
	// Timer that triggers the callback (blink LED) every x millisecond
	timer_init(1000, blink_leds); // Input the time interval in millisecond
	
	// Delay for a few seconds or do something
	for (volatile int i = 0; i < 5000000; i++) {
	}
	
	timer_reset(100);	// Change the interval

	while (1) {
	}
}
